host=localhost
port=8079
token=496193058
user=-1360753733

config1_price=1400
config2_price=2100
config3_price=3500

max_parallel_users=12
requests_per_minute_per_user=40
total_load_requests_per_minute=480
max_response_time_ms=670

load_threads=12
load_ramp_up_seconds=60
load_duration_seconds=300
load_throughput_per_thread_per_minute=40

stress_ramp_up_seconds=60
stress_duration_seconds=180
stress_throughput_per_thread_per_minute=40
stress_levels_users=12,15,18,21,24,27,30
